### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by rwelte** [roblan/shairport-sync-reader#2]
Hi,

unfortunately I'm not able to get your Code working ;-)
Could you please give me a peace of code, how you handle the events? E.g. to get the result of the event "meta"

Thanks in advance!

**Comment by roblan** [comment]
```
const reader = new ShairportReader({ path: '/tmp/shairport-sync-metadata' });
reader.on('meta', (data) => { console.log(data); });
```
should work

**Comment by rwelte** [comment]
works :-)

Thanks a lot.

**Comment by roblan** [comment]
No problem :) happy to hear that someone is using it:)
